# Generated by Django 5.0.2 on 2024-03-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_exam_module_exam_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.IntegerField(verbose_name='etapa'),
        ),
    ]
